# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Driver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.0'
  pod 'SwiftyNotifications', '~>0.7.1'

  # Pods for Driver

  target 'DriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DriverUITests' do
    # Pods for testing
  end

end
